
services:
  habitflow:
    image: l8tenever/habbit:latest
    container_name: habitflow
    restart: unless-stopped
    ports:
      - "9995:5000"
    volumes:
      - habit_data:/app/data
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:////app/data/habitflow_v3.db

volumes:
  habit_data:
